# =====================
# APPLICATION
# =====================
spring.application.name=padelefoca
server.port=8080

# =====================
# BASE DE DONNEES SQL SERVER
# =====================
spring.datasource.url=jdbc:sqlserver://localhost:50247;databaseName=padelefoca;encrypt=false;trustServerCertificate=true
spring.datasource.username=padelefoca
spring.datasource.password=Padelefoca123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# =====================
# JPA / HIBERNATE
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# =====================
# SWAGGER
# =====================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# =====================
# JWT
# =====================
jwt.secret=padelefoca-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000